### ISSUE TITLE
Is it possible to create a Property for an ObservableCollection?

### ISSUE THREAD

**Issue by akshat157** [omikhailov/handyvalidation#2]
Hello! Thanks for creating this library, I am currently using it in a project and it is working well.

I have got into a situation where I want to create a Property for an `ObservableCollection`, using which I want to watch the `Count` property of the `ObservableCollection`. I am trying to use a `Custom` validation rule but it appears to me that my `OkButtonWatcher` does not react to the `.Add()` and `.Remove()` methods of an `ObservableCollection`.

Am I missing something? Or is it not possible to do so currently?

Thanks!

**Comment by omikhailov** [comment]
Hello,

You don't have to use Property in this case. It would be enough to define CustomValidator and call its Validate() method during the CollectionChanged event.

I hope this helps
